language: node_js
sudo: false
branches: 
  only: 
    - master
    - pre
node_js: 
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
before_install:
  - npm install -g grunt-cli
  - npm install -g testem
  - npm install -g bower
  - bower install
